import type { Meta, StoryObj } from '@storybook/react';
import { QRCode } from './QRCode';

const meta = {
  title: 'UI/WaitingRoom/QRCode',
  component: QRCode,
  parameters: {
    layout: 'centered',
  },
  argTypes: {
    joinCode: {
      description: 'The string used to generate the QR code',
    },
  },
} satisfies Meta<typeof QRCode>;

export default meta;

type Story = StoryObj<typeof QRCode>;

/**
 * Displays a string and the QR code generated by it. Used in the Waiting Room.
 */
export const Default: Story = {
  args: {
    joinCode: 'ABC123',
  },
};
