version: "3.8"

services:
  socket-gateway:
    build:
      context: .
      dockerfile: packages/socket-gateway/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - microservices

  match-making:
    build:
      context: .
      dockerfile: packages/match-making/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    networks:
      - microservices

  game-management:
    build:
      context: .
      dockerfile: packages/game-management/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    environment:
      - CHALLENGES_URL=http://challenges:3003
    networks:
      - microservices

  challenges:
    build:
      context: .
      dockerfile: packages/challenges/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3003:3003"
    networks:
      - microservices

  scoring:
    build:
      context: .
      dockerfile: packages/scoring/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3004:3004"
    networks:
      - microservices

  client:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - socket-gateway
      - match-making
      - game-management
      - challenges
      - scoring
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
