export const MATCH_MAKING_CHANNEL_PREFIX = 'matchMaking';

export const MATCH_MAKING_CHANNEL = {
  SUBSCRIBE: {
    RESPONSE_JOIN_MATCH: `${MATCH_MAKING_CHANNEL_PREFIX}.responseJoinMatch`,
    RESPONSE_CREATE_MATCH: `${MATCH_MAKING_CHANNEL_PREFIX}.responseCreateMatch`,
  },
  PUBLISH: {
    REQUEST_JOIN_MATCH: `${MATCH_MAKING_CHANNEL_PREFIX}.requestJoinMatch`,
    REQUEST_CREATE_MATCH: `${MATCH_MAKING_CHANNEL_PREFIX}.requestCreateMatch`,
    LEAVE_MATCH: `${MATCH_MAKING_CHANNEL_PREFIX}.leaveMatch`
  }
} as const;